### PR TITLE
Add userAssignedIdentity to AAD group

### LINKED ISSUE #857: Feature Request: Add user-assigned-identity to AAD group
When creating a user-assigned identity, it would be great if there was a way to automatically add the given user to a named AAD group. This would allow permissions to be assigned at deployment time.

I don't believe its possible to add members to groups through ARM so this, I believe would need to be a post-deploy action. Something like the following:

```fsharp
let myId = userAssignedIdentity {
  name "my-identity"
  add_to_ad_group "my-production-apps"
  add_to_ad_groups ["my-all-apps"; "my-commerce-apps"]
}
```

### PR DESCRIPTION
**Pull request by TheRSP**
This PR closes #857 

The changes in this PR are as follows:

* Added add_to_ad_group(s) operators to userAssignedIdentity builder
* Added IPostDeploy action to userAssignedIdentity

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [x] **Tested my code** end-to-end against a live Azure subscription.
* [x] **Updated the documentation** in the docs folder for the affected changes.
* [ ] **Written unit tests** against the modified code that I have made.
* [x] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [x] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

If I haven't completed any of the tasks above, I include the reasons why here:
- I can't find any other PostDeploy tests and am not sure how to unit test it due to the dependency on Az.

Below is a minimal example configuration that includes the new features, which can be used to deploy to Azure:

```fsharp
    userAssignedIdentity {
        name "my-test-identity"
        add_to_ad_group "my-apps" // This AAD group must exist before the deployment is run
    }
```

### CODE REVIEW

**Comment by TheRSP** [comment]
Manual test results using `userassignedidentity.fsx` by modifying the add_to_group line
<details>
<summary>(Control) No groups</summary>
```
Compatible version of Azure CLI 2.29.1 detected
Checking Azure CLI logged in status... you are already logged in, nothing to do.
Using subscription '***' (***).
Creating resource group aad-identity-group (1/1)...
Deploying ARM template (please be patient, this can take a while)...
All done, now parsing ARM response to get any outputs...
Press any key to continue . . .
```
</details>
<details>
<summary>Add to group</summary>
```
Compatible version of Azure CLI 2.29.1 detected
Checking Azure CLI logged in status... you are already logged in, nothing to do.
Using subscription '***' (***).
Creating resource group aad-identity-group (1/1)...
Deploying ARM template (please be patient, this can take a while)...
Getting object id for identity 'my-test-identity'
Adding identity 'my-test-identity' (***) to group '***'...OK: my-test-identity added to group '***'
All done, now parsing ARM response to get any outputs...
Press any key to continue . . .
```
</details>

<details>
<summary>Add to group already containing member</summary>
```
Compatible version of Azure CLI 2.29.1 detected
Checking Azure CLI logged in status... you are already logged in, nothing to do.
Using subscription '***' (***).
Creating resource group aad-identity-group (1/1)...
Deploying ARM template (please be patient, this can take a while)...
Getting object id for identity 'my-test-identity'
Adding identity 'my-test-identity' (***) to group '***'...OK: my-test-identity already in group '***'
All done, now parsing ARM response to get any outputs...
Press any key to continue . . .
```
</details>
<details>
<summary>Non-existent AAD group</summary>
```
Compatible version of Azure CLI 2.29.1 detected
Checking Azure CLI logged in status... you are already logged in, nothing to do.
Using subscription '***' (***).
Creating resource group aad-identity-group (1/1)...
Deploying ARM template (please be patient, this can take a while)...
Getting object id for identity 'my-test-identity'
Adding identity 'my-test-identity' (***) to group 'my-aad-group'...Farmer.FarmerException: ERROR: No group matches the name of 'my-aad-group'

   at Farmer.Exceptions.raiseFarmer[a](String msg) in C:\dev\farmer\src\Farmer\Result.fs:line 7
   at Farmer.Deploy.execute(String resourceGroupName, FSharpList`1 parameters, IDeploymentSource deployment) in C:\dev\farmer\src\Farmer\Deploy.fs:line 285   at <StartupCode$FSI_0001>.$FSI_0001.main@()
Stopped due to error
```
</details>

**Comment by TheRSP** [comment]
Not that I could find. There is also this question which implies it's not
possible:
https://docs.microsoft.com/en-us/answers/questions/214227/can-we-add-users-group-azure-ad-using-arm-template.html

**Comment by TheRSP** [comment]
I thought the whole point of PostDeploy actions was to do things exactly like this from the builder? Similar to webapp's `zip_deploy` or storageAccount's `use_static_website`. Is the plan not to control PostDeploy tasks on the builders anymore?

Or is the concern the location of the logic rather than the addition of an operator in the builder?

**Comment by isaacabraham** [comment]
I'm in two minds here. I'm not specifically opposed to this as a post-deploy action personally - it's not the end of the world if some bits go into the CLI as well as ARM - as long as everything that *can* go into ARM, does. Then again, for the AD side of things, we already have some CLI helpers - could this not be one of them?

I'm not sure I have the answer here. I think maybe it's about the declarative nature of "I want to create this identity, it's part of these groups" as a declarative statement - in which case this might be fine. This is the approach we took for the upload app stuff.

**Comment by TheRSP** [comment]
I was hoping to achieve the declarative statement as mentioned by isaac but I do see that this would be confusing for users who only use Farmer as an ARM generator (rather than a deployment tool). 
If we were to make this an Az Helper, I was wondering if adding a keyword such as `post_deploy` might be acceptable to allow us to maintain this declarative nature without the confusion? Maybe something like the following?
```
userAssignedIdentity {
    name "my-test-identity"
    post_deploy (AzHelpers.addIdentityToActiveDirectoryGroup "my-apps")
}
```

I'm assuming that `post_deploy` will take a `UserAssignedIdentityConfig -> unit` so that the called function would still have access to the configured identity object.

**Comment by martinbryant** [comment]
Hi @TheRSP - can we look at getting the conflicts dealt with? Thanks

**Pull request closed without merging**
