### PR TITLE
[Azure Machine Learning] Add workspace support - WIP

### PR DESCRIPTION
**Pull request by lqdev**
This PR closes issue #398 

The changes in this PR are as follows:

* Add Azure Machine Learning ARM resource

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [ ] **Tested my code** end-to-end against a live Azure subscription.
* [ ] **Updated the documentation** in the docs folder for the affected changes.
* [ ] **Written unit tests** against the modified code that I have made.
* [ ] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [ ] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

If I haven't completed any of the tasks above, I include the reasons why here:

### CODE REVIEW

**Comment by isaacabraham** [comment]
@lqdev great stuff. I've marked this PR as a draft (rather than just appending WIP) - once it's ready to go, you can convert it to a full PR and we're review it together.

**Comment by isaacabraham** [comment]
@lqdev do you need a hand getting this going again?

**Comment by lqdev** [comment]
@isaacabraham Got caught up with a few things. Picking back up in December.

**Comment by isaacabraham** [comment]
Sounds good :-) If you'd like, I'm happy to merge from master into this PR branch to get things compiling again

**Comment by lqdev** [comment]
That would be great. Thanks :)

**Comment by isaacabraham** [comment]
@lqdev this is now up to date with the latest master :-)

**Comment by isaacabraham** [comment]
@lqdev I'm closing this as clean up - this PR is over six months old and stale - but if you want a hand to get it ready, let me know.

**Pull request closed without merging**
