### PR TITLE
Only prompt for AZ login if required.

### PR DESCRIPTION
**Pull request by isaacabraham**

### CODE REVIEW

**Comment by isaacabraham** [comment]
@forki this should remove logins unless necessary.

**Comment by forki** [comment]
Hugs

**Comment by forki** [comment]
Can I pass user and password?

**Comment by isaacabraham** [comment]
@forki show me the command line args you would send - we can add it if needed

**Comment by forki** [comment]
let args = sprintf "login -u \"%s\" -p \"%s\"" user pw
        runAZ args |> ignore

**Comment by isaacabraham** [comment]
Yes, you could. I'm not sure that this is best practice though and therefore I'm not convinced it's something we should bake in (might be totally wrong here - if Azure CLI offers it, can it really be that bad?) - I think you should look at using a [service principal](https://docs.microsoft.com/en-us/cli/azure/reference-index?view=azure-cli-latest#az-login) instead. And we could add that in, too.

**Comment by forki** [comment]
The service principal also uses -u and -p

Isaac Abraham <notifications@github.com> schrieb am Di., 14. Apr. 2020,
09:20:

**Comment by isaacabraham** [comment]
And tenant. :-)

But yes, true. We could make tenant optional.

**Pull request merged**
