### PR TITLE
Update to build and test with dotnet 6.0 SDK

### PR DESCRIPTION
**Pull request by ninjarobot**
Testing build pipeline with .NET 6.0.

### CODE REVIEW

**Comment by forki** [comment]
please wait with this until the task {} compiler fix landed in .NET SDK

**Comment by mattgallagher92** [comment]
The `task` computation expression bug that Steffen is referring to is https://github.com/dotnet/fsharp/issues/12359

**Comment by isaacabraham** [comment]
@ninjarobot any objections to us moving back to targeting a single TFM (netstandard2) rather than both NS2 and Net5? It adds around 50% to the build time.

**Comment by isaacabraham** [comment]
@ninjarobot at the time it was to remove the dependency on System.Text.Json (which is included in .NET 5) but in reality I'm not sure it's needed. Perhaps at some point in the future we'll move off of NS2 but I don't see that happening anytime soon.

**Comment by isaacabraham** [comment]
@ninjarobot could you merge from master into this branch? another merge conflict and I don't know enough about the YAML to confidently do the merge myself - sorry :-(

**Comment by isaacabraham** [comment]
I'm actually not sure we really need to wait on the `task { }` fix as we don't use any asynchronicity anywhere in the codebase.

**Comment by isaacabraham** [comment]
Thank you!

**Pull request merged**
