### PR TITLE
Azure DevOps NuGet Deployments -  attempt 2/N

### PR DESCRIPTION
**Pull request by ctolkien**
Have introduced Distinct `Stages` here, as I think the `Environment` wasn't running distcintly per job.

🙏 to the yaml gods.

### CODE REVIEW

**Comment by ctolkien** [comment]
image
Looking a bit better @isaacabraham ?

**Comment by isaacabraham** [comment]
Sweet :-) I'll merge this when we do the next RC. One question: when I ran the "non stage" version in, I saw this:

https://compositional-it.visualstudio.com/Farmer/_build/results?buildId=5081&view=logs&j=6dc3a5d1-ff8f-5d9a-0044-995331e18ea7&t=f2db4cb8-dab2-5bce-95fc-74894f83c3d2&l=19

i.e. when it came to trying the push, it warned: `[warning]No packages matched the search pattern.`.

**Comment by ctolkien** [comment]
Looks like the condition to create the package was skipped:
image

**Comment by isaacabraham** [comment]
Thank you - let's try it out!

**Comment by isaacabraham** [comment]
@ctolkien what does that condition mean? I'm seeing it again now - that second check looks to me like it will always fail?

**Comment by isaacabraham** [comment]
OK - just trying to figure out why vmImage is null. Is that even a proper variable? https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

**Comment by isaacabraham** [comment]
Success - the variable was actually 'imageName' . It all worked. Thank you **very much**.

**Pull request merged**
