### PR TITLE
MIT License

### PR DESCRIPTION
**Pull request by CaringDev**
As asked for in https://twitter.com/isaac_abraham/status/1178030847833841665?s=21

### CODE REVIEW

**Comment by CaringDev** [comment]
@isaacabraham @mikhailshilkov @Dzoukr could you all LGTM this? Your approval is needed as you all contributed to the code already.

**Comment by mikhailshilkov** [comment]
I'm certainly okay with MIT

**Comment by isaacabraham** [comment]
Me too.

**Comment by isaacabraham** [comment]
This fixes #19

**Comment by Dzoukr** [comment]
Of course! :)

**Comment by isaacabraham** [comment]
@CaringDev thanks :-)

**Pull request merged**
