### PR TITLE
#351 Depends_on as a list

### PR DESCRIPTION
**Pull request by MNie**
Fixes: #351 

I'm not sure that marking `IBuilder` is also a good idea since we would need then to always cast to an `IBuilder` so instead of writing:

```fsharp
depends_on [ builder ]
```

we would need to write:

```fsharp
depends_on [ builder :> IBuilder ]
```

@isaacabraham any thoughts/hints?

### CODE REVIEW

**Comment by isaacabraham** [comment]
@MNie Yes, we see the same issue with `add_resources` - because F# doesn't implicitly upcast to common interfaces (@cartermp am I right that there's plans to change this in the future?) you have to explicitly do this.

I've thought about moving to an SRTP approach and looking for the appropriate fields on the records as the other way around this, or having all builders return an IBuilder rather than config records - but this strikes me as somewhat more opaque so I would rather avoid doing that if possible.

**Comment by isaacabraham** [comment]
I was assuming that the list option would be added as an overload though, rather than replacing the original single item method.

**Comment by cartermp** [comment]
> am I right that there's plans to change this in the future?

Maybe. But unlikely to happen any time soon.

**Comment by MNie** [comment]
@isaacabraham I go the easy way then. I created overload methods that accepts lists:

- `DependsOn (state: 'config, resources: ResourceName list)`,
- `DependsOn (state: 'config, builders: IBuilder list)`,
- `DependsOn (state: 'config, resources: IArmResource list)`

I added some unit tests to see how it could be used + update documentation. Is there something else left to do here?

**Comment by isaacabraham** [comment]
That's great @MNie thank you. I'll test this out and then merge.

**Pull request merged**
