### PR TITLE
Wip PostgreSQL support.

### PR DESCRIPTION
**Pull request by hravnx**
This is a very very WiP first stab at adding PostgreSQL support to Farmer, as per issue #147 

This is merely intended to get some feedback on approach/direction etc.

One big question I have, is what would the correct testing strategy be here?

I've modelled it closely on the existing MSSql support, but there are no tests for that, or at least none that I could find. Also, there is apparently no client library from Microsoft for PostgreSQl (there is one for SqlServer). So I guess the best we can do is to compare the resulting json template with some expected content? And is there an example of how best to do that?

Or what would you suggest?

### CODE REVIEW

**Comment by isaacabraham** [comment]
Hey. I think, if there's no official MS SDK (and I have doubts as to how much they represent the "golden source of truth" anyway), then yes, I suggest your best bit is to simply compare fields on the generated JSON with expected values. I think that there are a few examples of this in the tests I did, but if not, this is a good opportunity to come up with a good pattern for doing so :-)

**Comment by dburriss** [comment]
@hravnx if I recall correctly I didn't end up using any client reference for the ContainerRegistery tests. I just used straight JObject to inspect. The asserts were overkill but I was experimenting with some ideas to protect the tests from change.

**Comment by isaacabraham** [comment]
The extra benefit we get from using the client libraries is that this proves that the template we emit conforms to Microsoft's own types. Without that, we confirm that we generate the JSON that *we* expect, but not more than that.

**Comment by isaacabraham** [comment]
@hravnx if this is a WIP, can you convert the PR to draft?

**Comment by hravnx** [comment]
I can, and I have

**Comment by dburriss** [comment]
@isaacabraham good point.

**Comment by hravnx** [comment]
So it works now, in that all tests pass, and I have verified that I can create an actual riunning PostgreSQL service through the Azure CLI.

There's a bunch of tests and a sample script in the samples folder.

Support for creating an actual database on the server is still missing, but I wanted to get some feedback before adding it in, and you can create a database by running SQL commands against the instance.

**Comment by isaacabraham** [comment]
Great stuff! Let's get this in :-)

I'll merge this up into the cleanup branch immediately afterwards (which will necessitate moving your code around, but that's fine, I'll do that) and then push that in. We can probably do a release shortly afterwards.

**Pull request merged**
