### PR TITLE
Make zones configurable for Virtual Machines

### PR DESCRIPTION
**Pull request by collinkruger**
This PR closes https://github.com/CompositionalIT/farmer/issues/791

The changes in this PR are as follows:

* Makes `zones` configurable on VMs

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [ ] **Tested my code** end-to-end against a live Azure subscription.
* [ ] **Updated the documentation** in the docs folder for the affected changes.
* [ ] **Written unit tests** against the modified code that I have made.
* [ ] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [ ] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

If I haven't completed any of the tasks above, I include the reasons why here:

### CODE REVIEW

**Comment by collinkruger** [comment]
@ninjarobot, LGTM!

**Comment by martinbryant** [comment]
Hi @collinkruger - can we look at getting the conflicts dealt with and the PR submitted on this one? Thanks

**Comment by collinkruger** [comment]
Hi @martinbryant, unfortunately between work/school/family I won't have time to work on this until January 2024. Would you like for me to go ahead and close it until then?

**Comment by martinbryant** [comment]
@collinkruger @ninjarobot thanks for the replies and will close now

**Pull request closed without merging**
