### PR TITLE
Fantomas 6

### PR DESCRIPTION
**Pull request by nojaf**
The changes in this PR are as follows:

* Update the fantomas dotnet tool to v6.0.0-alpha-008 (See [blogpost](https://blog.nojaf.com/2023/03/28/fantomas-six-legendary-formatter/))
* Format all the code

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [ ] **Tested my code** end-to-end against a live Azure subscription.
* [x] **Updated the documentation** in the docs folder for the affected changes.
* [ ] **Written unit tests** against the modified code that I have made.
* [ ] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [x] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

Hi there,

We are trying to get some in-the-field feedback on our next major release.
If memory serves correctly someone was interested in the Stroustrup style for Farmer as it could be a good fit when there is a lot of configuration. I could be wrong and this was more about when using Farmer versus the actual Farmer codebase.
V6 has made a lot of improvements in that area, so I'm curious to hear your thoughts.

### CODE REVIEW

**Comment by nojaf** [comment]
Still found a minor issue: https://github.com/fsprojects/fantomas/issues/2806

**Comment by isaacabraham** [comment]
Thanks so much - this is definitely highly desired - the stroustrup style makes life a lot easier, particularly in the `Arm` namespace because we make heavy use of nested list comprehensions, and without stroustrup it pushes everything across more and more.

**Comment by nojaf** [comment]
Thanks for confirming, I'll get back to you later this week once we have fixed the found issue.

**Comment by isaacabraham** [comment]
Would also be great to have `fsharp_newline_before_multiline_computation_expression = true` set as well.

(As an aside, isn't the setting named backwards? Surely it should be false for e.g

```fsharp
let x = foo {
    bar 123
}
```

**Comment by nojaf** [comment]
Yeah, naming is hard 😅. 

`fsharp_newline_before_multiline_computation_expression = true` by default. See https://fsprojects.github.io/fantomas/docs/end-users/Configuration.html#fsharp_newline_before_multiline_computation_expression

What we are going for:

There will be a newline before the computation expression by default.
```fsharp
    let something = // Here is the newline before the computation expression
        task {
            let! thing = otherThing ()
            return 5
        }
```

If you don't want the CE to go to the next line (aka you don't want the newline):
```fsharp
let something = (* no newline before the CE *) task {
    let! thing = otherThing ()
    return 5
}
```

So, you want the setting to be `false`?

**Comment by martinbryant** [comment]
Hi @nojaf - can we look at getting the conflicts dealt with and the PR submitted on this one? Thanks

**Comment by nojaf** [comment]
@martinbryant done!

**Comment by martinbryant** [comment]
Amazing @nojaf thanks :)

**Comment by nojaf** [comment]
You can check out the version differences at https://github.com/fsprojects/fantomas/blob/main/CHANGELOG.md.

I'll go ahead and close this PR. Whether this gets merged or not doesn't really matter to me anymore. If someone else ever wants to do the upgrade, they can use this PR as a reference. 😊

**Pull request closed without merging**
