### PR TITLE
Deploying multiple resource groups at once

### LINKED ISSUE #215: Support for resource groups at the subscription level
ARM supports the concept of subscription level resources, where instead of the ARM template being deployed to a resource group, the ARM template itself contains one or more resource groups, with other resources nested underneath.
See
https://samcogan.com/deploying-resource-groups-with-arm-templates/
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deploy-to-subscription

Support for resource groups at the subscription level would be nice - complex templates sometimes end up spanning multiple resource groups due to limitations in various resources. E.g. database server is shared between multiple projects and in a separate resource group, App Service Plan must be placed in separate resource group to end up in correct Web Space etc.

### PR DESCRIPTION
**Pull request by TheRSP**
This PR closes #215

The changes in this PR are as follows:

* Add `resourceGroup` builder for resourcegroups and nested deployments
* Added concept of Subscription-scoped deployments

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [x] **Tested my code** end-to-end against a live Azure subscription.
* [x] **Updated the documentation** in the docs folder for the affected changes.
* [x] **Written unit tests** against the modified code that I have made.
* [x] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [x] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

---
Outstanding issues for review:
* I'm not sure I like the idea of the scope keyword in the armBuilder. It feels to me like there should be a seperate top-level builder for subscription-scoped deployments but I couldn't think of a good name for this. I have left the scope keyword in for discussion.
* I'm not familiar with the support for outputs in ARM/Farmer so have not added support for these at present

### CODE REVIEW

**Comment by isaacabraham** [comment]
@TheRSP Closed?

**Comment by TheRSP** [comment]
I closed this PR as I no longer think that the implementation in this PR is a good solution. I have a plan for what I believe to be a much better implementation and have started work on this.

**Comment by isaacabraham** [comment]
ok cool

**Comment by isaacabraham** [comment]
happy to go through design approach if you'd like (in the issue might be a good place to do it from top-down perspective)

**Pull request closed without merging**
