### PR TITLE
#411 add branding

### LINKED ISSUE #411: Brand the console output
When running Farmer, we should emit some basic information at the start e.g.

```bash
==================================================
Farmer 1.2 beta 2
Repeatable Deployments in Azure made Easy!
==================================================
```

### PR DESCRIPTION
**Pull request by MNie**
This PR closes #411 

The changes in this PR are as follows:

* add branding

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [x] **Tested my code** end-to-end against a live Azure subscription.
* [x] **Updated the documentation** in the docs folder for the affected changes.
* [x] **Written unit tests** against the modified code that I have made.
* [x] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [X] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

If I haven't completed any of the tasks above, I include the reasons why here:
- It couldn't be tested on Azure(?). I test it locally:
image

I'm curious about where to add branding. I add it to `quickWrite` but what with the `toJson`/`toFile` they are visible from the module so we should also add them there?
Also, if this is the right way to do the coloring inside of `Console.Write`?
- Documentation update not needed,
- Unit tests not needed,
- I would update Release Notes when code would be accepted.

CC: @isaacabraham

### CODE REVIEW

**Comment by isaacabraham** [comment]
Please just put the release notes in the PR. Then I can accept the PR and the notes will naturally come in.

**Comment by isaacabraham** [comment]
> I'm curious about where to add branding

I would say that any time you "run" the application it should show. You could maybe put it as the first thing in the application startup.

**Comment by MNie** [comment]
@isaacabraham I updated the release notes. I also added branding to the `deploy`.

**Comment by isaacabraham** [comment]
I think if you just put it into the Program.fs startup then that would catch everything rather than having to do it on a case-by-case basis?

**Comment by MNie** [comment]
> I think if you just put it into the Program.fs startup then that would catch everything rather than having to do it on a case-by-case basis?

So we simply want to add branding to the `Sample` only?
image

**Comment by isaacabraham** [comment]
Doh. Good point - I'm being stupid, Farmer is just a class library! Hmmm. Then I would say just in the core functions - deploy, validate, whatif etc. (these will be ones that hit Az CLI).

**Comment by MNie** [comment]
@isaacabraham 

`execute`, `whatif`, `tryExecute`, `tryWhatIf`, `tryValidate` all of them execute `prepareForDeployment` where I add `branding`.

I also add it to the `quickWrite` from `Writer.fs`.

**Comment by isaacabraham** [comment]
Thank you!

**Pull request merged**
