### PR TITLE
Add in new network libraries

### PR DESCRIPTION
**Pull request by admodras**
This PR closes #

The changes in this PR are as follows:

* ...
* ...
* ...

I have read the [contributing guidelines](CONTRIBUTING.md) and have completed the following:

* [ ] **Tested my code** end-to-end against a live Azure subscription.
* [ ] **Updated the documentation** in the docs folder for the affected changes.
* [ ] **Written unit tests** against the modified code that I have made.
* [ ] **Updated the [release notes](RELEASE_NOTES.md)** with a new entry for this PR.
* [ ] **Checked the coding standards** outlined in the [contributions guide](CONTRIBUTING.md) and ensured my code adheres to them.

If I haven't completed any of the tasks above, I include the reasons why here:

### CODE REVIEW

**Comment by isaacabraham** [comment]
@admodras Thanks for putting this in - really appreciate the new network resources (as will @ninjarobot)!

However, we really need to separate these different features into separate PRs in order to deal with them in a manageable fashion - each of them needs to be reviewed separately, documented and tested - plus we need to think about how to integrate them with existing builders etc.

Thanks!

**Comment by admodras** [comment]
Yes - this is going to be split up so they are each in separate PRs and we need to update tests and documentation. Still working through a few issues and unfortunately time hasn't allowed us to quite finish off this PR.  We need to integrate with existing builder moving forward and will see if I can carve out time with @ninjarobot to at least get the first library completed and then i can step through the rest after i have something to work off of.

**Comment by admodras** [comment]
We really should have a separate PR that upgrades to dotnet 5.0 so i don't need to have that as part of this PR. We added it for now because that is what we are using and would be cleaner if Farmer as a whole was running off of dotnet5.0 so i can just focus on the new network features.

**Comment by isaacabraham** [comment]
@admodras there was a long-standing NET 5 PR already. I actually canned it this weekend because it was doing too much and have made a lighter one that will go in today.

**Comment by isaacabraham** [comment]
@admodras Farmer now supports .NET 5. Happy to work with you when you have time to get the other network resources in.

**Comment by 23min** [comment]
Seems like `dotnet new farmer` still creates a netcorapp3.1 project (installed the template a few days ago). 
Updating the libs manually to .net5 breaks the Minecraft sample.
This .net churn is just so frustrating. Everything's perpetually broken. Sorry for the frustration ;)

**Comment by isaacabraham** [comment]
@ninjarobot what should we do with this PR - I imagine that some of the features in this PR have ended up in Farmer already by some means or other.

**Comment by js-mode** [comment]
@ninjarobot - you can go ahead a close this PR (I don't have permissions to).  I no longer need it for reference and should be covered by the work from Eric.

**Pull request closed without merging**
