### PR TITLE
Allow an IArmResource list to be added to a resource group.

### PR DESCRIPTION
**Pull request by Ryan-Palmer-CIT**
The changes in this PR are as follows:

* Added an IArmResource list accepting function to the Resource Group builder

The motivation for the change is that I wanted to add a list of role assignments to a resource group.

### CODE REVIEW

**Comment by Ryan-Palmer-CIT** [comment]
I've just realised this broke all the other builders as they pick the wrong overload, bear with me...

**Comment by Ryan-Palmer-CIT** [comment]
Ok - after talking to @isaacabraham  I have added a separate function for lists of ARM resources, `add_arm_resources`. Overloading the existing `add_resources` caused all builders to require explicit casting to IBuilder.

**Comment by isaacabraham** [comment]
Just needs docs adding for the builder.

**Comment by Ryan-Palmer-CIT** [comment]
Ok added the docs bit

**Comment by isaacabraham** [comment]
Thanks @Ryan-Palmer-CIT !

**Pull request merged**
