### PR TITLE
Support for zip_deploy for FunctionApp + docs

### PR DESCRIPTION
**Pull request by Dzoukr**
Hello friend,

I had an idea for adding support for `zip_deploy` also for Azure Functions (using https://docs.microsoft.com/en-us/cli/azure/functionapp/deployment?view=azure-cli-latest).

I tried to follow existing convences, but please review and change as you like. ;)

### CODE REVIEW

**Comment by isaacabraham** [comment]
Thanks - looks good to me :-) Have you tested it out on functions / web app? That way I know what needs checking.

**Comment by Dzoukr** [comment]
I didn't - currently fighting with Azure permissions. If you could check it would be great, but as contributor it's my responsibility so if you don't want to do it, just keep the PR in progress and I'll do it when Azure problems are over. 😄

**Comment by isaacabraham** [comment]
It's fine, I can check quickly enough. If you could send me a working functions app that I could use for testing, that would be great.

**Comment by Dzoukr** [comment]
[FunctionApp.zip](https://github.com/CompositionalIT/farmer/files/4877043/FunctionApp.zip)

Here you are @isaacabraham, sorry for the delay.

It's single function app (HTTP trigger) with replying on all endpoints.

**Comment by Dzoukr** [comment]
Ok, I just tried and seems to be working smoothly 🎉

**Comment by Dzoukr** [comment]
Please, @isaacabraham, any idea when the new release with this PR will be available on Nuget? I am converting all pipelines to use Farmer and zip_deploy for funcs would be handy. 😄

**Comment by ChendrayanV** [comment]
I have trouble in deploying the function app using Farmer. Please share the example.

**Comment by isaacabraham** [comment]
@Dzoukr this should be released now?

**Comment by isaacabraham** [comment]
@ChendrayanV There is a video on [this page](https://compositionalit.github.io/farmer/deployment-guidance/) of the docs illustrating how to do zip deployment for web apps - functions behave in exactly the same way as far as I know (@Dzoukr  can you confirm?)

**Comment by Dzoukr** [comment]
Yup. There is no difference between zip_deploy for web apps and functions (from API perspective).

**Comment by ChendrayanV** [comment]
@Dzoukr and @isaacabraham  Thanks for the swift response. Indeed, I followed the same and failed to get it working

```FS
let azureFunctions = functions {
    name "iCollabrains-Prod"
    //setting "SCM_DO_BUILD_DURING_DEPLOYMENT" "true"
    zip_deploy @"C:\Temp\iCollabrains-Prod.zip"
}
```

**_Error:
FS0708: This control construct may only be used if the computation expression builder defines a 'For' method_** 

Then though of doing it using webApp resource

```FS
let azFuncDeploy = webApp {
    name "iCollabrains-Prod"
    zip_deploy @"C:\Temp\iCollabrains-Prod.zip"
    depends_on azureFunctions
}
```
Still failed. I know I am doing something wrong. Not sure, how to fix it up!

**Comment by isaacabraham** [comment]
I've just tested this out with a brand new app and it does not give any compile error:

image

What version of the Farmer package are you referencing? Try updating to the latest one.

**Pull request merged**
