### PR TITLE
Adds whatif capability to Deploy

### PR DESCRIPTION
**Pull request by dburriss**
This feature resolves CompositionalIT/farmer#140

### CODE REVIEW

**Comment by isaacabraham** [comment]
@dburriss is this draft or ready to go?

**Comment by dburriss** [comment]
Well it works. Was more just a question of whether you wanted the feature :)

**Comment by isaacabraham** [comment]
Yes, for sure. We should iterate on it though - in the older (REST) API implementation, I had the code parse through the JSON and give nice F# DUs for the results. Happy to do that later though, unless you want to dig that code out yourself.

**Comment by dburriss** [comment]
Could do. For me this is a good first step. It is just informational. One thing I did not check was error codes. First iteration would be making sure it can be used as a gate. I think it is useful as is so happy to merge in if you happy.

**Pull request merged**
