### PR TITLE
Yield resources/For overloads

### PR DESCRIPTION
**Pull request by Shmew**
As per our Twitter convo here's a few (non-breaking it looks like) changes that can potentially improve the syntax. You'll want to look at how the merging is done because you might want to change that behavior.

Goes from:
```fsharp
let myEh = eventHub {
    name "first-hub"
    namespace_name "allmyevents"

    sku Standard
    enable_zone_redundant
    enable_auto_inflate 3
    add_authorization_rule "FirstRule" [ Listen; Send ]
    add_authorization_rule "SecondRule" AllAuthorizationRights

    partitions 2
    message_retention_days 3
    add_consumer_group "myGroup"
}

let secondHub = eventHub {
    name "second-hub"
    link_to_namespace "allmyevents"
    partitions 1
    message_retention_days 1
}

let deployment = arm {
    location Location.NorthEurope
    add_resource myEh
    add_resource secondHub
}
```

into this:

```fsharp
let deployment = arm {
    location Location.NorthEurope
        
    eventHub {
        name "first-hub"
        namespace_name "allmyevents"
    
        sku Standard
        enable_zone_redundant
        enable_auto_inflate 3
        add_authorization_rule "FirstRule" [ Listen; Send ]
        add_authorization_rule "SecondRule" AllAuthorizationRights
    
        partitions 2
        message_retention_days 3
        add_consumer_group "myGroup"
    }

    eventHub {
        name "second-hub"
        link_to_namespace "allmyevents"
        partitions 1
        message_retention_days 1
    }
}
```

It also enables `for x in xs do` syntax like requested in #99

```fsharp
let deployment = arm {
    location Location.NorthEurope
        
    for i in [ 1 .. 2 ] do
        eventHub {
            name (sprintf "hub-%i" i)
            link_to_namespace "allmyevents"
            partitions 1
            message_retention_days 1
        }
}
```

### CODE REVIEW

**Comment by isaacabraham** [comment]
Whoa. Holy moly, that's not even what I was thinking of in our discussion! I tried this a long time ago and couldn't get it to work.

**Comment by isaacabraham** [comment]
Interestingly, a unit test is breaking locally for this.

**Comment by isaacabraham** [comment]
If it's ok with you @Shmew I'll keep this locally as it's very useful for me to see how you've achieved this - it's definitely something I want to incorporate into v2.

**Comment by Shmew** [comment]
Yeah I never intended for it to be merged, just as an example for how the API could be changed. Hope it helps!

**Pull request closed without merging**
