### PR TITLE
Add tryExecute method

### PR DESCRIPTION
**Pull request by dpraimeyuu**
Naive (hopefully pragmatic enough) approach for solving #120

### CODE REVIEW

**Comment by isaacabraham** [comment]
First - thanks :-) Second - would it be better to flip this on it's head and have the `execute` version as throwing the exception, and the `try` variant returning a `Result`? @forki - this was your idea, what do you think?

**Comment by dpraimeyuu** [comment]
@isaacabraham I thought about approach you mentioned, but wouldn't it be a breaking change?

**Comment by isaacabraham** [comment]
Whilst we're not at v1, whilst we should obviously look to avoid breaking changes, I'm not too fussed - some of the iterations in the past weeks have been sweeping changes to the deployment API and this would be a relatively minor change.

**Comment by dpraimeyuu** [comment]
Ok, renamed them 👍

**Comment by isaacabraham** [comment]
Just need to fix up the unit test now :-)

**Comment by isaacabraham** [comment]
Ah you were too quick! :-)

**Comment by isaacabraham** [comment]
Thank you :-)

**Pull request merged**
