### PR TITLE
Only trigger page builds for docs subdirectory

### PR DESCRIPTION
**Pull request by SeanKilleen**
Supports #175.

### CODE REVIEW

**Comment by SeanKilleen** [comment]
@isaacabraham @hravnx I think this should do it.

**Comment by SeanKilleen** [comment]
Oh, may have been a timing issue -- looks like someone added it in the time it took me to submit the PR. 😆

**Comment by isaacabraham** [comment]
Yeah I thought I'd eventually get my hands dirty :-)

**Comment by isaacabraham** [comment]
Thanks for helping again though!

**Pull request closed without merging**
